# Generated by Django 2.1.2 on 2018-11-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required.', max_length=150, verbose_name='email address'),
        ),
    ]
