# Generated by Django 2.1.2 on 2018-11-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20181112_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_login_date'),
        ),
    ]
