# Generated by Django 2.1.2 on 2018-11-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20181127_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_date',
        ),
    ]
