# Generated by Django 2.1.2 on 2018-11-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_auto_20181112_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='created_by_id'),
        ),
    ]
