# Generated by Django 2.1.2 on 2018-11-22 10:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(error_messages={'unique': 'A subject with that name already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='subject')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('tracker', models.CharField(choices=[('0', 'Defect'), ('1', 'Feature'), ('2', 'Patch')], max_length=14, verbose_name='tracker')),
                ('status', models.CharField(choices=[('0', 'New'), ('1', 'In Progress'), ('2', 'Solved'), ('3', 'Close')], max_length=14, verbose_name='status')),
                ('progress', core.models.DecimalFieldRange(decimal_places=2, default=0.0, max_digits=3)),
                ('update', models.DateTimeField(default=0, verbose_name='update')),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(error_messages={'unique': 'A subject with that name already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='subject')),
                ('place', models.TextField(blank=True, null=True, verbose_name='place')),
                ('date_and_time', models.DateTimeField(default=0, verbose_name='date and time')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A project with that name already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A role with that name already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='name')),
                ('edit_project', models.BooleanField(default=False, verbose_name='edit project')),
                ('create_issue', models.BooleanField(default=0, verbose_name='create issue')),
                ('edit_issue', models.BooleanField(default=0, verbose_name='edit issue')),
                ('delete_issue', models.BooleanField(default=0, verbose_name='delete issue')),
                ('create_meeting', models.BooleanField(default=0, verbose_name='create meeting')),
                ('edit_meeting', models.BooleanField(default=0, verbose_name='edit meeting')),
                ('delete_meeting', models.BooleanField(default=0, verbose_name='delete meeting')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
    ]
