# Generated by Django 2.1.2 on 2018-11-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AddField(
            model_name='role',
            name='create_issue',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='create_issue'),
        ),
        migrations.AddField(
            model_name='role',
            name='create_meeting',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='create_meeting'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by_id',
            field=models.IntegerField(default=0, null=True, verbose_name='created_by_id'),
        ),
        migrations.AddField(
            model_name='role',
            name='delete_issue',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='delete_issue'),
        ),
        migrations.AddField(
            model_name='role',
            name='delete_meeting',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='delete_meeting'),
        ),
        migrations.AddField(
            model_name='role',
            name='edit_issue',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='edit_issue'),
        ),
        migrations.AddField(
            model_name='role',
            name='edit_meeting',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='edit_meeting'),
        ),
        migrations.AddField(
            model_name='role',
            name='edit_project',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='edit_project'),
        ),
    ]
