# Generated by Django 2.1.2 on 2018-11-27 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20181122_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='subject',
            field=models.CharField(error_messages={'unique': 'A issue with that subject already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='subject'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('member', 'role'), ('member', 'project')},
        ),
    ]
