# Generated by Django 2.1.2 on 2018-11-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181120_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='create_issue',
            field=models.BooleanField(default=0, verbose_name='create_issue'),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_meeting',
            field=models.BooleanField(default=0, verbose_name='create_meeting'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_by_id',
            field=models.IntegerField(default=0, verbose_name='created_by_id'),
        ),
        migrations.AlterField(
            model_name='role',
            name='delete_issue',
            field=models.BooleanField(default=0, verbose_name='delete_issue'),
        ),
        migrations.AlterField(
            model_name='role',
            name='delete_meeting',
            field=models.BooleanField(default=0, verbose_name='delete_meeting'),
        ),
        migrations.AlterField(
            model_name='role',
            name='edit_issue',
            field=models.BooleanField(default=0, verbose_name='edit_issue'),
        ),
        migrations.AlterField(
            model_name='role',
            name='edit_meeting',
            field=models.BooleanField(default=0, verbose_name='edit_meeting'),
        ),
        migrations.AlterField(
            model_name='role',
            name='edit_project',
            field=models.BooleanField(default=0, verbose_name='edit_project'),
        ),
    ]
