# Generated by Django 2.1.2 on 2018-11-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181120_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='edit_project',
            field=models.BooleanField(default=0, verbose_name='edit project'),
        ),
    ]
