# Generated by Django 2.1.2 on 2018-11-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181120_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='created_by_id',
            field=models.IntegerField(default=0, verbose_name='created_by_id'),
        ),
    ]
