# Generated by Django 2.1.2 on 2018-11-21 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20181120_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(error_messages={'unique': 'A subject with that name already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='subject')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('tracker', models.CharField(choices=[(0, 'Defect'), (1, 'Feature'), (2, 'Patch')], max_length=14, verbose_name='tracker')),
                ('status', models.CharField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Solved'), (3, 'Close')], max_length=14, verbose_name='status')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='progress')),
                ('update', models.DateTimeField(default=0, verbose_name='update')),
                ('project_id', models.IntegerField(default=0, verbose_name='created_by_id')),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
            },
        ),
    ]
