# Generated by Django 2.1.2 on 2018-11-21 13:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='progress',
            field=core.models.DecimalFieldRange(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('0', 'New'), ('1', 'In Progress'), ('2', 'Solved'), ('3', 'Close')], max_length=14, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tracker',
            field=models.CharField(choices=[('0', 'Defect'), ('1', 'Feature'), ('2', 'Patch')], max_length=14, verbose_name='tracker'),
        ),
    ]
