# Generated by Django 2.1.2 on 2018-11-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181121_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project_id',
        ),
    ]
