# Generated by Django 2.1.2 on 2018-11-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
